### ISSUE TITLE
Novidades do not appear (keeps loading)

### ISSUE THREAD

**Issue by whatbeato** [carrismetropolitana/android#3]
Boas :)

I suppose this issue is caused by the new website update (I love the new website! Kudos to you João! It looks really good!), which causes the images of the Novidades section in the Mais tab.

I'm using app version 2024.10.30 (1730325413) on a Samsung Galaxy Z Fold 4 running Android 14. I have recorded two versions, one with the phone folded, and one with the phone unfolded.

https://github.com/user-attachments/assets/92d3d509-3d27-4739-abd3-e3b6c67a2c5f

https://github.com/user-attachments/assets/9f5289d5-42d3-4986-99af-79966709be1b

Thank you,
Afonso :)

**Comment by joaodcp** [comment]
Olá! :)

Thanks for the heads up! This was fixed earlier today and has been released on the Play Store as of a few hours ago!
The new version is 2024.11.25 (1732561965). If you can, please update to the newest version and check if the issue persists.

Thank you again! 🚌

**Comment by whatbeato** [comment]
Working after update!
